plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Add this line
mathjax: true

name: Philip LaPorte
tagline: mathematics phd candidate, uc berkeley
career-objective: I am a third-year graduate student at UC Berkeley, co-advised by <a href="https://www.stat.berkeley.edu/~evans/" target="_blank">Steven Evans</a> and <a href="https://www.martinnowak.com/" target="_blank">Martin Nowak</a> (Harvard). I am interested in the mathematics of evolution, especially evolutionary game theory and social behavior. Recently I have been working on repeated games and direct reciprocity. I am very grateful to be supported by an NSF Graduate Research Fellowship. 
color-theme: red # red or blue
avatar-filename: Philip_Laporte2.JPG # Change to your avatar's filename
url: philiplaporte.github.io
baseurl: 
paginate: 5
paginate_path: "/blog/page:num/"

# Social Information
social:
  email: 
    visibility: true
    mail: philip_laporte@berkeley.edu
  github: 
    visibility: false
    handle: a
  linkedin: 
    visibility: false
    handle: a
  twitter: 
    visibility: false
    handle: a

# Collections
collections:
  experience:
    output: false
    sort_by: order
  education:
    output: false
    sort_by: order
  projects:
    output: false
    sort_by: year
  skills:
    output: false
    sort_by: order
  publications:
    output: true
    sort_by: year
  volunteerexperience:
    output: false
    sort_by: order
  certifications:
    output: false
    sort_by: year
  achievements:
    output: false
    sort_by: year

# About Page Options
collection_option:
  experience: 
    label: Experience
    visibility: false
  education: 
    label: education
    visibility: true
  projects: 
    label: Projects
    visibility: false
  skills: 
    label: Technical Skills
    visibility: false
  publications: 
    label: publications
    visibility: true
  volunteerexperience: 
    label: Volunteer Experience
    visibility: false
  certifications: 
    label: talks and presentations
    visibility: true
  achievements: 
    label: Achievements
    visibility: false

navigation:
- title: about
  url: /
#- title: Blog
#  url: /blog/
#- title: Contact
#  url: /contact

include:
  - _pages

exclude:
  - readme.md

# Defaults
defaults:
  - scope:
      path: ''
      type: posts
    values:
      permalink: /:categories/:year/:month/:title
      layout: post
      comments: true
  - scope:
      path: ''
      type: projects
    values:
      permalink: /projects/:title
      layout: project
      comments: false
  - scope:
      path: ''
      type: publications
    values:
      permalink: /publications/:title
      layout: publication
      comments: false

# Disqus Comment
disqus:
  shortname: academic-portfolio # Change with your own disqus shortname

# Contact Form
formspree:
  endpoint: https://formspree.io/f/xdorkgkv # Change with your own form's endpoint

# Google Analytics
google_analytics: UA—XXXXXXXX-X